#ifndef GLOBALS_H
#define GLOBALS_H

#define SCREEN_W 1280
#define SCREEN_H 720

#define PHYSICS_STEPS 8

#define MAX_ENTITIES 5000

enum class RenderLayer: uint8_t{
    DEFAULT             = 0,
    BACKGROUND_TILES_GROUND,
    BACKGROUND_TILES_SOLID,
    BACKGROUND_DECORATIONS,
    Y_SORT,
    ENEMIES,
    PLAYER,
    PROJECTILES,
    PARTICLES,
    UI,
    MAX_LAYERS,
};

// BACKGROUND_TILES_GROUND,
// BACKGROUND_TILES_WALL,
// BACKGROUND_DECORATIONS,

#endif // GLOBALS_H
